### ISSUE TITLE
IsInt gives Warning: NumberFormatter::parse()

### ISSUE THREAD

**Issue by khloukrada** [zendframework/zend-i18n#10]
When letter is parsed for validation IsInt, a warning is generated instead of issuing error self::INVALID. The warning is Warning: NumberFormatter::parse(): Number parsing failed in ..\vendor\zendframework\zendframework\library\Zend\I18n\Validator\IsInt.php on line 121

**Comment by froschdesign** [comment]
This was fixed with [version 2.3.4](https://github.com/zendframework/zend-i18n/releases/tag/release-2.3.4). See: https://github.com/zendframework/zendframework/pull/6598
