### ISSUE TITLE
PHP 7.4compatibility

### ISSUE THREAD

**Issue by trasher** [zendframework/zend-i18n#113]
- [ x ] I was not able to find an [open](https://github.com/zendframework/zend-i18n/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-i18n/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [ x ] This is not a question. (Questions should be asked on [chat](https://zendframework.slack.com/) ([Signup here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

Running on PHP 7.4 (which has reached RC1 last week), depreciations are shown.

### Expected results

Works with php 7.4

For the error I've seen, the fix should be:
```difff
--- ./src/Translator/Loader/Gettext.php.patch	2019-09-09 10:01:11.452282178 +0200
+++ ./src/Translator/Loader/Gettext.php	2019-09-09 10:03:33.676984850 +0200
@@ -139,7 +139,7 @@ class Gettext extends AbstractFileLoader
         }
 
         // Read header entries
-        if (array_key_exists('', $textDomain)) {
+        if ($textDomain->offsetExists('')) {
             $rawHeaders = explode("\n", trim($textDomain['']));
 
             foreach ($rawHeaders as $rawHeader) {
```

**Comment by michalbundyra** [comment]
Fixed in #122
