### ISSUE TITLE
Check Documentation For Other Things

### ISSUE THREAD

**Issue by GeeH** [zendframework/zend-i18n#25]
# Check docs for other problems

> TLDR; Cast your eye over the documetation for any problems **not** covered in the other issues

Things slip through the net, so check the documentation for other problems that have been missed. Common other problems include
- Bullet lists (should be single `*` then space at the start of line)
- Inline code - should be marked by three backticks at start and finish
- `bookdown.json` file is correctly formated and has the right escaping
- Links between documentation using RST have been stripped
- Any other RST has been removed correctly
- Anything and everything not covered

If you end up fixing the same problem over and over, please ping [Gary Hockin](https://twitter.com/GeeH) - we may be able to add bespoke issue for that problem, or fix in automated capacity

**Comment by froschdesign** [comment]
@GeeH 
I think, we have a bigger problem: in all converted documentation files the method descriptions are missing.

Example: I18n View Helpers - CurrencyFormat Helper http://framework.zend.com/manual/current/en/modules/zend.i18n.view.helpers.html#basic-usage

reStructuredText:

```
.. function:: currencyFormat(float $number [, string $currencyCode = null [, bool $showDecimals = null [, string $locale = null [, string $pattern = null ]]]])
   :noindex:

   Format a number

   :param $number: The numeric currency value.

   :param $currencyCode: (Optional) The 3-letter ISO 4217 currency code indicating the currency to use. If unset, it will use the default value ``null`` (``getCurrencyCode()``).

   :param $showDecimals: (Optional) Boolean false as third argument shows no decimals. If unset, it will use the default value ``true`` (``shouldShowDecimals()``).

   :param $locale: (Optional) Locale in which the currency would be formatted (locale name, e.g. en_US). If unset, it will use the default locale (``Locale::getDefault()``).

   :param $pattern: (Optional) Pattern string that is used by the formatter. If unset, it will use the default value ``null`` (``getCurrencyPattern()``).

   :rtype: string
```

https://github.com/zendframework/zf2-documentation/blob/master/docs/src/modules/zend.i18n.view.helper.currency.format.rst

The same for Zend\Form (e.g. [Form elements](https://github.com/zendframework/zend-form/blob/master/book/zend.form.elements.md)) and all other components.

**Comment by froschdesign** [comment]
@GeeH 
I found another problem: all validators are duplicated.
- all validators are included in [one file](https://github.com/zendframework/zend-i18n/blob/master/doc/book/zend.i18n.validators.md)
- and separated ([Alnum, Alpha, Float, Int](https://github.com/zendframework/zend-i18n/tree/master/doc/book))

**Comment by GeeH** [comment]
@froschdesign 
Thanks Frank,

Question - do I need to tweak the conversion script and re-convert,or can this be fixed by hand please?

**Comment by froschdesign** [comment]
@GeeH 
I think, extending the conversion script is the way we should go, because the method descriptions with the `.. function::` syntax are used 307 times.

In following components:
- Zend\Cache
- Zend\Filter
- Zend\Form
- Zend\I18n
- Zend\Mvc
- Zend\Serializer
- Zend\Validator
- Zend\View

**Comment by froschdesign** [comment]
Here are 3 proposals for formatting the method descriptions with markdown:

## Version 1

|  | Method description |
| --- | --- |
| **Declaration** | `currencyFormat(float $number [, string $currencyCode = null [, bool $showDecimals = null [, string $locale = null [, string $pattern = null ]]]])` |
| **Description** | Format a number |
| **Parameters** |  |
| `$number` | The numeric currency value. |
| `$currencyCode` | (Optional) The 3-letter ISO 4217 currency code indicating the currency to use. If unset, it will use the default value `null` (`getCurrencyCode()`). |
| `$showDecimals` | (Optional) Boolean false as third argument shows no decimals. If unset, it will use the default value `true` (`shouldShowDecimals()`). |
| `$locale` | (Optional) Locale in which the currency would be formatted (locale name, e.g. en_US). If unset, it will use the default locale (`Locale::getDefault()`). |
| `$pattern` | (Optional) Pattern string that is used by the formatter. If unset, it will use the default value `null` (`getCurrencyPattern()`). |
| **Return type** | string |

## Version 2

**Method description**

`currencyFormat(float $number [, string $currencyCode = null [, bool $showDecimals = null [, string $locale = null [, string $pattern = null ]]]])`

Format a number

|  | Parameters |
| --- | --- |
| `$number` | The numeric currency value. |
| `$currencyCode` | (Optional) The 3-letter ISO 4217 currency code indicating the currency to use. If unset, it will use the default value `null` (`getCurrencyCode()`). |
| `$showDecimals` | (Optional) Boolean false as third argument shows no decimals. If unset, it will use the default value `true` (`shouldShowDecimals()`). |
| `$locale` | (Optional) Locale in which the currency would be formatted (locale name, e.g. en_US). If unset, it will use the default locale (`Locale::getDefault()`). |
| `$pattern` | (Optional) Pattern string that is used by the formatter. If unset, it will use the default value `null` (`getCurrencyPattern()`). |

**Return type**

string

## Version 3

**Method description**

`currencyFormat(float $number [, string $currencyCode = null [, bool $showDecimals = null [, string $locale = null [, string $pattern = null ]]]])`

Format a number

**Parameters**
- **`$number`** The numeric currency value.
- **`$currencyCode`** (Optional) The 3-letter ISO 4217 currency code indicating the currency to use. If unset, it will use the default value `null` (`getCurrencyCode()`).
- **`$showDecimals`** (Optional) Boolean false as third argument shows no decimals. If unset, it will use the default value `true` (`shouldShowDecimals()`).
- **`$locale`** (Optional) Locale in which the currency would be formatted (locale name, e.g. en_US). If unset, it will use the default locale (`Locale::getDefault()`).
- **`$pattern`** (Optional) Pattern string that is used by the formatter. If unset, it will use the default value `null` (`getCurrencyPattern()`).

**Return type**

string
