### ISSUE TITLE
AbstractPluginManager Dependency error

### ISSUE THREAD

**Issue by FraGoTe** [zendframework/zend-i18n#36]
PHP Fatal error:  Class 'Zend\ServiceManager\AbstractPluginManager' not found in vendor/zendframework/zend-i18n/src/Translator/LoaderPluginManager.php on line 58,

**Comment by weierophinney** [comment]
@FraGoTe I'm assuming you're using zend-i18n standalone.

As such, please notice the suggestions that Composer lists when you install zend-18n. One of them is zendframework/zend-servicemanager, which is required when using the translator subcomponent. (The dependency is not marked as required, as there are utilities in the zend-i18n component that can be used standalone without usage of the translator sub-component.)
