### ISSUE TITLE
zend-view should be required in composer.json

### ISSUE THREAD

**Issue by michalbundyra** [zendframework/zend-i18n#39]
Library [zend-view](https://github.com/zendframework/zend-view) should be required in `composer.json` because it is used in `Zend\I18n\View\Helper` classes:
- https://github.com/zendframework/zend-i18n/blob/master/src/View/Helper/AbstractTranslatorHelper.php#L14
- https://github.com/zendframework/zend-i18n/blob/master/src/View/Helper/CurrencyFormat.php#L15
- https://github.com/zendframework/zend-i18n/blob/master/src/View/Helper/DateFormat.php#L16

**Comment by froschdesign** [comment]
It's already included in the ["suggest" part](https://github.com/zendframework/zend-i18n/blob/master/composer.json#L39):

```
"zendframework/zend-view": "You should install this package
to use the provided view helpers"
```
