### ISSUE TITLE
PhoneNumber validator seems to be broken for at least country DE

### ISSUE THREAD

**Issue by ghost** [zendframework/zend-i18n#79]
I expected the validator to match the whole value given to isValid (or atleast a space-trimmed version of it), but it seems to also issue number parts as valid.

Using the following simple test program

```
require('vendor/autoload.php');                                                 
                                                                                
use Zend\I18n\Validator\PhoneNumber;                                            
                                                                                
$phonenumbers = [                                                               
    '12345678 67890',                                                           
    '12345678a67890',                                                           
    'ab 12345678',                                                              
    '12345678cd',                                                               
    'ab12345678',                                                                 
    'ab-12345678-cd',                                                           
];                                                                              
                                                                                
$pv = new PhoneNumber([                                                         
    'allowed_types' => ['fixed', 'mobile'],                                     
    'country' => 'DE'                                                           
]);                                                                             
                                                                                
foreach ($phonenumbers as $pn) {                                                
    var_dump($pv->isValid($pn));                                                
} 
```

I get with PHP 7.1

```
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
```

I'd be ok with the first one, but the others are just wrong IMHO.

The source of the problem seems to be preg_match's alternative (|) handling: Line-start (^) and line-end ($) matcher are handled for each alternative individually, thus in your regex strings the ^ and $ are only used for the first and the last alternative respectively.

Quoting the documentation: "Circumflex (^) need not be the first character of the pattern if a number of alternatives are involved, but it should be the first thing in each alternative in which it appears if the pattern is ever to match that branch. [..] Dollar ($) need not be the last character of the pattern if a number of alternatives are involved, but it should be the last item in any branch in which it appears. " [1].

From my point of view, there are 3 possibilities:
1. Add ^ and $ to each alternative
2. Use a non-capturing group like ^(?:a|b|c)$
3. It seems that \A and \Z match the beginning/end of the whole string, thus \Aa|b|c\Z should also work

Kind regards, Heiko

[1] http://php.net/manual/en/regexp.reference.anchors.php

**Comment by froschdesign** [comment]
@htto
Sorry for the very late response. I will check this problem.

Thank you for reporting!
