### ISSUE TITLE
PhoneNumber Brasil with problems 

### ISSUE THREAD

**Issue by apoca** [zendframework/zend-i18n#82]
Doesn't work for some new number in Brasil, like:

+5551992493178

This number exists:

<pre>
{
  "caller_name": null,
  "country_code": "BR",
  "phone_number": "+5551992493178",
  "national_format": "(51) 99249-3178",
  "carrier": {
    "mobile_country_code": "724",
    "mobile_network_code": "05",
    "name": "Claro",
    "type": "mobile",
    "error_code": null
  },
  "add_ons": null,
  "url": "https://lookups.twilio.com/v1/PhoneNumbers/+5551992493178?Type=carrier"
}
</pre>

**Comment by malukenho** [comment]
@apoca can you send us a unit test for this failure please?

**Comment by apoca** [comment]
As you can see an example with a really Brazilian number: +5551992529385 I think this happens always with the same carrier "Claro".

![captura de ecra 2017-09-21 as 15 31 10](https://user-images.githubusercontent.com/5594091/30701357-fa991b00-9ee1-11e7-9683-6a627ed64d2e.png)

**Comment by malukenho** [comment]
@apoca sorry for the late reply. It indeed is failing on php7, but seems to work on php5 versions.

**Comment by apoca** [comment]
I’ll try (test) with php5 but it’s impossible change my environment to this version in production.

**Comment by malukenho** [comment]
@apoca could you provide the actual code that is causing the trouble?

**Comment by rwrz** [comment]
#103 should fix that.. =)
