### ISSUE TITLE
Translator ignore text domain specified when adding translations

### ISSUE THREAD

**Issue by BobRenald** [zendframework/zend-i18n#83]
The documentation (https://docs.zendframework.com/zend-i18n/translation/#translating-messages) says:

> The text domain parameter is the one you specified when adding translations. If omitted, the "default" text domain will be used.

But the following code doesn't work:

```
$translator = new Translator();
$translator->addTranslationFile(
   'gettext',
   __DIR__ . '/../locale/en/LC_MESSAGES/messages.mo', 
   'messages',
   'en'
);
$translator->setLocale('en');
echo $translator->translate('hello_world');
```

You have to to specify again the textDomain in the translate() method, like following:

`echo $translator->translate('hello_world', 'messages');`

**Comment by froschdesign** [comment]
@BobRenald 
I think you misunderstand the text domain parameter.

Usage for "default" text domain:
```php
$translator->addTranslationFile(
   'gettext',
   'file.mo'
);
echo $translator->translate('hello_world');
```

Usage for any other text domain:
```php
$translator->addTranslationFile(
   'gettext',
   'file.mo',
   'my_text_domain'
);
echo $translator->translate('hello_world', 'my_text_domain');
```

You always add the translation to a text domain. Without specifying the text domain, "default" is used. If you call the `translate` method, then "default" is used also here as standard value:

https://github.com/zendframework/zend-i18n/blob/f10380553a9ffd8a2f18e3ba67f70a7510fc58c9/src/Translator/Translator.php#L353
