### ISSUE TITLE
Wrong pattern for french mobile phone

### ISSUE THREAD

**Issue by rphilippe** [zendframework/zend-i18n#85]
Hello,

The pattern used for the french mobile phone is wrong: https://github.com/zendframework/zend-i18n/blob/f10380553a9ffd8a2f18e3ba67f70a7510fc58c9/src/Validator/PhoneNumber/FR.php#L16

Acccording to [googlei18n/libphonenumber](https://github.com/googlei18n/libphonenumber/blob/e35ea659977b85eef9192b1cba5849c3ac305e46/resources/PhoneNumberMetadata.xml#L7926) line 7926 it should be `/(?:6\d|7[3-9])/`.

Tried it and it's working fine. Any ETA on a fix?

**Comment by froschdesign** [comment]
@rphilippe 
Sorry for the very late response. I will try to update all patterns.

Thank you for reporting!
