### ISSUE TITLE
DateFormat with timezone change.

### ISSUE THREAD

**Issue by datasage** [zendframework/zend-i18n#98]
- [X] I was not able to find an [open](https://github.com/zendframework/zend-i18n/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-i18n/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [X] This is not a question. (Questions should be asked on [chat](https://zendframework.slack.com/) ([Signup here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

Provide a narrative description of what you are trying to accomplish.
We use zend view to generate emails as part of a batch job. The timezone is changed, with date_default_timezone_set()  between successive renders of templates.

The dateFormat view helper, caches the date formatter within the service. However it does not use the timezone as part of that hash key.

### Code to reproduce the issue

template.phtml file
```php
<?= $this-dateFormat($this->date, \IntlDateFormatter::DATE_MEDIUM) ?>

```

```php
$view = new ViewModel()l
$view->setTerminal(true);
$view->setTemplate('template');

date_default_timezone_set('America/Chicago');
$date = new \DateTime('2018-01-01');
$view->date = $date;

echo $renderer->render($view);

date_default_timezone_set('America/New_York');
$date = new \DateTime('2018-01-01');
$view->date = $date;

echo $renderer->render($view);
```

### Expected results
Display Jan 1, 2018 in both cases.

### Actual results
Jan 1, 2018 in the first case, but Dec 31, 2017 in the second case.

**Comment by froschdesign** [comment]
I think, this is a bug. But we need an unit test to confirm the problem.

Good catch! 👍
